language: python
sudo: required
dist: trusty
python:
  - "3.6"
  - "3.7-dev"
install:
  - sudo apt-get install openssh-client
  - eval "$(ssh-agent -s)"
  - pip install --upgrade .[test]
script:
  - pytest tests/
